#!/bin/sh

#!/bin/sh

###
# Instructions:
# Press <C-x>, then a key from one of the cases
###

###
# Note:
# All script operations are slower than the built-in
# ones so prefer the latter when possible.
###

# Prefer dunstify, fall back to notify-send.
if command -v dunstify >/dev/null 2>&1; then
    notify() {
        dunstify "$@"
    }
elif command -v notify-send >/dev/null 2>&1; then
    notify() {
        notify-send "$@"
    }
else
    notify() {
        printf '%s\n' "$*" >&2
    }
fi

notify_image() {
    image="$1"
    shift

    if command -v dunstify >/dev/null 2>&1; then
        dunstify -i "$image" "$@"
    elif command -v notify-send >/dev/null 2>&1; then
        notify-send -i "$image" "$@"
    else
        printf '%s\n' "$*" >&2
    fi
}

mkdir -p ~/.trash/

while read -r file
do
        fpath=$file
        case "$1" in
        "d")
            mv "$fpath" ~/.trash
            notify "$file moved to ~/.trash"
            ;;
        "D")
            rm -rf "$fpath"
            notify "$file deleted permanently"
            ;;
        "f")
            # horizontal flip
            convert -flop "$fpath" "$fpath"
            ;;
        "i")
            notify "[$file] $(identify "$fpath" | cut -d' ' -f1), $(identify "$fpath" | cut -d' ' -f2), $(identify "$fpath" | cut -d' ' -f3), $(ls -lh "$fpath" | cut -d' ' -f5)"
            ;;
        "r")
            convert -rotate 90 "$fpath" "$fpath"
            ;;
        "R")
            convert -rotate 270 "$fpath" "$fpath"
            ;;
        "c")
            xclip -selection clipboard -t image/png -i "$fpath"
            notify_image "$fpath" "Image copied to clipboard" "$file"
            ;;
        "w")
            sed -i "/feh/c\feh --bg-scale $(abspath "$file")" ~/.xinitrc
            feh --bg-scale "$file"
            notify "$file set as wallpaper"
            ;;
        esac
done
