#!/bin/bash

### Requirements:
# rofi

### Description:
# This is a rofi menu that houses the `sshot` script.
# It selects some basic parameters via the list and feeds them
# to the script.
function _rofi_menu() {
    local menu_text=`echo -e "🖵     Entire screen
✀     Region 
🖵     In 3 seconds
🖵     In 5 seconds
🖵     In 10 seconds
✖     Cancel" | rofi -dmenu -i -p "Screenshot" -location 3 -width 20 -lines 6 -hide-scrollbar -font "Roboto Condensed 11" -yoffset 34 -xoffset`
    local mode=""
    local delay=0
    if [[ $menu_text == *[E\|e]ntire* ]]; then
        mode="-f"
    elif [[ $menu_text == *[R\|r]egion* ]]; then
        echo
    elif [[ $menu_text == *3* ]]; then
        delay=3
        mode="-f"
    elif [[ $menu_text == *5* ]]; then
        delay=5
        mode="-f"
    elif [[ $menu_text == *10* ]]; then
        delay=10
        mode="-f"
    elif [[ $menu_text == *[C\|c]ancel* ]]; then
        exit 1
    fi
    sshot $mode -d $delay
}

_rofi_menu $@
