#!/bin/bash

### Requirements:
# rofi

### Description:
# This is a rofi menu that houses the `sshot` script.
# It selects some basic parameters via the list and feeds them
# to the script.
function _rofi_menu() {
    local _menu_text=`echo -e "    🖵     Entire screen
     ✀     Region 
     🯳      In 3 seconds
     🯵      In 5 seconds
    🯱 🯰   In 10 seconds
     ✖       Cancel" | rofi -dmenu -i -p "Screenshot" -location 3 -width 20 -hide-scrollbar -font "Roboto Condensed 11" -yoffset 34 -xoffset`
    local _mode=""
    local _delay=0
    if [[ $_menu_text == *[E\|e]ntire* ]]; then
        _mode="-f"
    elif [[ $_menu_text == *[R\|r]egion* ]]; then
        echo
    elif [[ $_menu_text == *3* ]]; then
        _delay=3
        _mode="-f"
    elif [[ $_menu_text == *5* ]]; then
        _delay=5
        _mode="-f"
    elif [[ $_menu_text == *10* ]]; then
        _delay=10
        _mode="-f"
    fi
    sshot $_mode -d $_delay
}

_rofi_menu $@
