#!/bin/bash

_run_for() {
    local delay=$1 duration=$2
    shift 2
    sleep "$delay"
    setsid "$@" &
    local pid=$!
    sleep "$duration"
    kill -INT -- "-$pid"
    wait "$pid"
}

[ -f ~/.bash/scripts/add_dir_to_path.sh ] && . ~/.bash/scripts/add_dir_to_path.sh
_run_for "$@"
