#!/bin/bash

### Requirements:
# imagemagick
# xclip (optional)
# dunst | notify-send (optional)

function _help() {
    local filename=`basename $0`
    echo     "Usage:"
    echo -e  "~~~~~~\n"
    echo -e  "$ ${filename%.*} [-f|--full] [-d|--delay N] [-p|--purge] [-h|--help]\n"
    echo     "No arguments:"
    echo -e  "    User draws a rectangle and the screenshot of that region is taken\n"
    echo     "[-f|--full]"
    echo -e  "    Takes a screenshot of the entire screen\n"
    echo     "[-d|--delay N]"
    echo -e  "    Wait N sec before doing anything\n"
    echo     "[-p|--purge]"
    echo -e  "    Clear all saved screenshots\n"
    echo     "[-h|--help]"
    echo -e  "    Print this help menu and exit\n"
    echo     "Notes:"
    echo -e  "~~~~~~"
    echo     "    Automatically copies the screenshot to clipboard if xclip is installed."
    echo     "    Stores the last $max_sshots screenshots as $out_dir${common_prefix}<date>__XX.png"
}

### Parameters:
# Run _sshot -h to view them
function _sshot() {
    local out_dir=/home/$USER/Pictures/screenshots/
    mkdir -p $out_dir
    local common_prefix=sshot_
    local prefix=$common_prefix`date +%d_%m_%Y_%H:%m`__
    local sshot_paths=(`ls $out_dir$common_prefix*`)
    local len_sshot_paths=${#sshot_paths[@]}
    local max_sshots=15
    
    # hold up to 15 screenshot files
    if [ $len_sshot_paths -gt $[$max_sshots-1] ]; then
        # shift all indexed files to the right to make space for new file
        for i in `seq $[$len_sshot_paths-1] 1`; do
            mv ${sshot_paths[i-1]} ${sshot_paths[i]} 
        done
        local newfile=${sshot_paths[0]}
    else
        # else append to the end
        local newfile=$out_dir$prefix`printf "%02d.png" "$len_sshot_paths"`
        sshot_paths+=($newfile)
    fi
    
    # parameters to read from user - default values
    local cmd="import $newfile"
    local delay_sec=0
    # parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h|--help)
                _help
                exit 0
                ;;
            -d|--delay)
                local delay_sec=$2
                shift # past argument
                shift # past value
                ;;
            -f|--full)
                cmd="import -window root $newfile"
                shift
                ;;
            -p|--purge)
                rm $out_dir${common_prefix}*
                exit 0
                ;;
            --default)
                cmd="import $newfile"
                shift # past argument
                ;;
            -*|--*)
                echo "Unknown option $1"
                _help
                exit 1
                ;;
            *)
                shift # past argument
                ;;
        esac
    done

    set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters
    # wait if necessary
    sleep $delay_sec
    # screenshot command
    eval $cmd
    local xclip_message=""
    has xclip && xclip -selection clipboard -t image/png -i ${newfile} \
              && xclip_message="copied to clipboard!"
    if has dunst; then
        dunstctl close all
        dunstify -u low -i $newfile "Screenshot at $newfile $xclip_message"
    elif has notify-send; then
        notify-send --expire-time=3000 -i $newfile $newfile "Screenshot at $newfile $xclip_message"
    fi
}

_sshot $@ &
