#!/bin/sh

######################################
# Instructions:
# Press <C-x>, then one of the following
# to perform a custom action
######################################
mkdir -p ~/.trash/

while read file
do
        case "$1" in
        "C-d")
			mv "$file" ~/.trash ;;
        "C-r")
			convert -rotate 90 "$file" "$file" ;;
        "C-c")
			echo -n "$file" | xclip -selection clipboard ;;
        "C-w")
			sed -i "/feh/c\feh --bg-scale $(pwd)/${file}" ~/.xinitrc;
			feh --bg-scale "$file" ;;
        esac
done

